version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆️"
      prefix-development: "⬆️"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/meeseeks-api"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆️"
      prefix-development: "⬆️"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/meeseeks-chat"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆️"
      prefix-development: "⬆️"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/meeseeks-cli"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆️"
      prefix-development: "⬆️"
      include: "scope"
