repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
  - repo: local
    hooks:
      - id: mypy-root
        name: mypy (root)
        entry: poetry run mypy
        language: system
        pass_filenames: false
      - id: mypy-api
        name: mypy (meeseeks-api)
        entry: bash -lc 'cd meeseeks-api && poetry run mypy'
        language: system
        pass_filenames: false
      - id: mypy-chat
        name: mypy (meeseeks-chat)
        entry: bash -lc 'cd meeseeks-chat && poetry run mypy'
        language: system
        pass_filenames: false
